import type { ApprovalDiffContext } from "../harness/diff-preview.js";

// Deterministic, templated spoken approval prompts — never generated by
// Claude, never a self-reported justification. Reuses whatever
// diff-preview.ts already computed (via ApprovalDiffContext) rather than
// recomputing line counts or reading files again.
export function generateSpokenApprovalPrompt(
  toolName: string,
  input: unknown,
  diffContext?: ApprovalDiffContext
): string {
  const i = (input ?? {}) as Record<string, unknown>;

  switch (toolName) {
    case "edit_file": {
      const path = String(i.path ?? "the file");
      let detail = "";
      if (diffContext) {
        detail = ` — ${diffContext.linesChanged} line${diffContext.linesChanged === 1 ? "" : "s"} changed`;
      }
      return `Edit ${path}${detail}. Approve?`;
    }

    case "write_file": {
      const path = String(i.path ?? "the file");
      return diffContext?.isNewFile === false ? `Overwrite ${path}. Approve?` : `Create ${path}. Approve?`;
    }

    case "delete_file":
      return `Delete ${String(i.path ?? "the file")}. Approve?`;

    case "move_file":
      return `Rename ${String(i.from ?? "?")} to ${String(i.to ?? "?")}. Approve?`;

    case "run_command":
      // The literal command string, never summarized or paraphrased.
      return `Run: ${String(i.command ?? "")}. Approve?`;

    default:
      return `Approve ${toolName}?`;
  }
}
